export type Stock={symbol:string;name:string;sector:string;price:number;change:number;marketCap:string;pe:string;pbv:string;dividendYield:string;thesis:string;catalysts:string[];risks:string[]};
export const stocks:Stock[]=[
{symbol:"BBCA",name:"Bank Central Asia",sector:"Banks",price:9875,change:1.12,marketCap:"Rp 1,215T",pe:"20.8x",pbv:"4.1x",dividendYield:"2.7%",thesis:"Quality compounder with strong funding franchise and resilient asset quality.",catalysts:["Loan growth","CASA growth","Dividend"],risks:["Valuation premium","Credit cycle"]},
{symbol:"BBRI",name:"Bank Rakyat Indonesia",sector:"Banks",price:4120,change:0.73,marketCap:"Rp 623T",pe:"11.7x",pbv:"2.1x",dividendYield:"6.1%",thesis:"Large retail and micro franchise with strong distribution and earnings leverage.",catalysts:["Micro recovery","NIM","Asset quality"],risks:["Micro credit quality","Funding costs"]},
{symbol:"BMRI",name:"Bank Mandiri",sector:"Banks",price:5925,change:-0.34,marketCap:"Rp 690T",pe:"10.5x",pbv:"2.0x",dividendYield:"4.5%",thesis:"Scale leader with diversified loan book and strong digital ecosystem.",catalysts:["Corporate lending","Fee income","Digital adoption"],risks:["NIM compression","Macro slowdown"]},
{symbol:"TLKM",name:"Telkom Indonesia",sector:"Telecommunications",price:2840,change:0.52,marketCap:"Rp 282T",pe:"15.2x",pbv:"2.0x",dividendYield:"5.8%",thesis:"Defensive cash-flow profile supported by connectivity and data demand.",catalysts:["Data traffic","Fiber monetization","Efficiency"],risks:["Competition","Capex intensity"]},
{symbol:"ASII",name:"Astra International",sector:"Conglomerate",price:5075,change:-0.18,marketCap:"Rp 205T",pe:"7.4x",pbv:"1.2x",dividendYield:"6.0%",thesis:"Diversified exposure to autos, financial services, heavy equipment and commodities.",catalysts:["Auto sales","Commodity cycle","Dividend"],risks:["Commodity weakness","Consumer slowdown"]},
{symbol:"ANTM",name:"Aneka Tambang",sector:"Basic Materials",price:3120,change:2.10,marketCap:"Rp 75T",pe:"14.9x",pbv:"2.4x",dividendYield:"1.8%",thesis:"Commodity leverage with strategic exposure to nickel and precious metals.",catalysts:["Gold prices","Nickel demand","Downstreaming"],risks:["Commodity volatility","Policy changes"]},
{symbol:"GOTO",name:"GoTo Gojek Tokopedia",sector:"Technology",price:72,change:1.41,marketCap:"Rp 86T",pe:"NM",pbv:"1.0x",dividendYield:"—",thesis:"Digital ecosystem with focus on monetization, efficiency and path to profitability.",catalysts:["Take rate","Cost discipline","Ecosystem growth"],risks:["Profitability execution","Competition"]}];
export const idx={value:8142.31,change:0.68};export function getStock(symbol:string){return stocks.find(s=>s.symbol===symbol.toUpperCase());}